"""Adding column email_id

Revision ID: da0d33ee67d7
Revises: 
Create Date: 2024-03-21 12:29:08.857186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da0d33ee67d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_id', sa.String(length=250), nullable=False))
        batch_op.create_unique_constraint(None, ['email_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email_id')

    # ### end Alembic commands ###
